Ttvz 91/pausa client webphone js
totalvoice/webphone-js pull request #2
Opened 2020-02-18 17:51 UTC by raphaelmacsabpf

Adiciona ao código de exemplo do webphone hidden as funções para pausar e despausar um ramal em todas as filas

2020-02-19 01:51 UTC, dilowagner requested changes

2020-02-19 01:51 UTC, dilowagner commented on webphone-hidden.html
> +            function pauseInQueue(queueId) {
@raphaelmacsabpf não seria interessante continuar o padrão que estava sendo utilizado? Em português...
Algo do tipo
pausarNaFila
despausarNaFila

Entendo, que fica um pouco estranho, mas nao perde o padrao que ja estava sendo criado... apesar do recstart e recstop hahaha

Mas em uma futura versao refatoramos isso...

2020-02-19 01:51 UTC, dilowagner commented on webphone-hidden.html
> +            function unpauseInQueue(queueId) {
@raphaelmacsabpf mesmo comentario acima...

2020-02-19 01:57 UTC, raphaelmacsabpf commented on webphone-hidden.html
> +            function pauseInQueue(queueId) {
Concordo. Realmente utilizei o padrão que vi do recStart e recStop e assumi que deveria ser em inglês. Providenciarei as alterações. Valeu Diego Wagner.

2020-02-21 14:33 UTC, joaohang approved these changes

2020-02-21 20:08 UTC, dilowagner approved these changes

2020-02-21 20:09 UTC, merged