[master] Adiciona exemplo dos eventos de pausa, despausa, entrada e saída da fila
totalvoice/webphone-js pull request #7
Opened 2020-03-05 21:24 UTC by raphaelmacsabpf

Adiciona eventos faltantes ao webphone hidden

2020-03-06 16:33 UTC, dilowagner requested changes

2020-03-06 16:33 UTC, dilowagner commented on webphone-REACT/index.js
> +    if(e.data.message == 'pausou_na_fila') {
@raphaelmacsabpf eu acharia interessante colocar no comentário assim:
// Evento emitido (ou disparado tanto faz) quando o ramal é pausado na fila

Acho que dá um noção melhor pro desenvolvedor não ficar perdido, talvez ele possa pensar que tenha que "chamar|postar" esse evento

2020-03-06 16:33 UTC, dilowagner commented on webphone-REACT/index.js
> +    if(e.data.message == 'pausou_na_fila') {
Faz sentido?

2020-03-06 19:45 UTC, raphaelmacsabpf commented on webphone-REACT/index.js
> +    if(e.data.message == 'pausou_na_fila') {
Faz sim. Modificações foram feitas, e enviadas no commit 0cf2950

2020-03-10 01:46 UTC, dilowagner approved these changes

2020-03-10 01:46 UTC, merged